### ISSUE TITLE
onset of 1 for a subregion doesn't pass check

### ISSUE THREAD

**Issue by ebergelson** [SeedlingsBabylab/audiowords#11]
32    *FAN: &=w4_19 . •0_1000•
33    %xcom:    eb manually changed first bullet end time back to 1000 so file will 
34      pass check
35    %xcom:    subregion 1 of 5 starts at 1 -- previous timestamp adjusted: was 1000
36

**Comment by andreiamatuni** [comment]
fixed with 8493cff68b7867d9ea72cc6922b8e9c57e18b92e
