### ISSUE TITLE
can we add the rank of the region to the subregion text?

### ISSUE THREAD

**Issue by ebergelson** [SeedlingsBabylab/audiowords#12]
is it straightforward to change the text in audiowords that gets printed to reflect the rank of the region, e.g. subregion 1 of 5 ends at 3900000 -- previous timestamp adjusted: was 3901190

becomes
subregion 1 of 5 (ranked 2 of 5) ends at 3900000 -- previous timestamp adjusted: was 3901190

**Comment by andreiamatuni** [comment]
the latest commit adds this to the subregion comments. It's only implemented for .cha's when running Load All (cha) right now. I'll add it to Load All (.cex) tomorrow.

**Comment by andreiamatuni** [comment]
fixed with 8c2cbce87e7ad8cd889e7d74d71c9fba97dc615f
