### ISSUE TITLE
first timestamp being 0_1

### ISSUE THREAD

**Issue by ebergelson** [SeedlingsBabylab/audiowords#14]
I thought we fixed this but, but I got this error in check in :+1: 
31    @Bg:  Pause 1
32    *SIL: 0 . •0_1•
34    %xcom:    subregion 1 of 5 starts at 1 -- previous timestamp adjusted: was 1380 [contains silent region: [2570975.899, 2652715.872] ]

All initial 0_1 timestamps should be changed to 0_1000  and a comment added. (if this is just a audiowords version issue lmk)

**Comment by andreiamatuni** [comment]
I thought this was changed in commit 8493cff68b7867d9ea72cc6922b8e9c57e18b92e....though after looking at this more closely it looks like that change didn't fix the issue at all. I'll fix this today to write 0_1000 and a comment. Just to clarify, the comment should be in addition to the subregion/silence comment that follows right? Something like:

"subregion/silence comment rewrote interval to 0_1, rewriting to 0_1000"

**Comment by ebergelson** [comment]
yup!

_Elika Bergelson, PhD_
Research Assistant Professor, University of Rochester
Center for Language Sciences | Brain and Cognitive Science Dept. |
www.bcs.rochester.edu/people/ebergelson | www.bcs.rochester.edu/seedlings/
Get a signature like this: Click here!
http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=

**Comment by andreiamatuni** [comment]
The latest commit fixes this

Example of silence comment rewrite:

@Bg:    Pause 1
*NOF:   0 . 0_1000
%xcom:  silence comment rewrote interval to 0_1, rewriting to 0_1000
%xcom:  silence 1 of 2 starts at 1000.0 -- previous timestamp adjusted: was 3540
%xdb:   average_dB="-27.59" peak_dB="-11.36"
*OLF:   0 . 3540_4920

Example of subregion comment rewrite:

@Bg:    Pause 1
*SIL:   0 . 0_800
%xdb:   average_dB="-38.66" peak_dB="-20.63"
*NOF:   0 . 800_1000
%xcom:  subregion comment rewrote interval to 0_1, rewriting to 800_1000
%xcom:  subregion 1 of 5  (ranked 1 of 5)  starts at 1000 -- previous timestamp adjusted: was 2460
%xdb:   average_dB="-38.51" peak_dB="-21.34"
*CXF:   0 . 2460_3260
