### ISSUE TITLE
IO Error Invalid Mode

### ISSUE THREAD

**Issue by URBabylab** [SeedlingsBabylab/audiowords#2]
![03_11_snap](https://cloud.githubusercontent.com/assets/11462259/8044589/aace2f6c-0dfb-11e5-90d2-c146a31b10dc.PNG)

Get the following error when I do Load_All on the 03_11 audio file. All the required files are there.

**Comment by andreiamatuni** [comment]
Was this issue closed because it was resolved?

**Comment by URBabylab** [comment]
Yep, the problem was that I closed the browse dialog without attaching a file.
