### ISSUE TITLE
Silence region not being recorded

### ISSUE THREAD

**Issue by URBabylab** [SeedlingsBabylab/audiowords#9]
37_06 should have created two silences but only one was written, in the wrong interval. I left the file for you on Lily/Desktop/Andrei/37_06

**Comment by URBabylab** [comment]
same issues are occurring with 07_12 and 39_06 found within Lily/Desktop/Sub_Files/Munna

**Comment by andreiamatuni** [comment]
fixed by ee025c245542d2f6e1b5f1353f507af3d7c0cd3a
